### ISSUE TITLE
usage of hprose

### ISSUE THREAD

**Issue by pokemonhan** [Lao-liu/laravel-hprose#1]
I am using laravel version Laravel Framework 5.4.19 and
 followed the step of configuration and run then I got with these errors please help me how to solve it.
**FatalErrorException in HproseClientWrapper.php line 85:
syntax error, unexpected 'use' (T_USE), expecting identifier (T_STRING)**

**Comment by Lao-liu** [comment]
@harrisdt15f  hi, sorry for this bug. it so low error.  -_______- !!  i was updated for this bug, please update!
